language: c
os: linux
dist: bionic

before_install:
 - sudo apt-get install -y git wget libncurses-dev flex bison gperf python python-click python-pip python-setuptools python-serial python-cryptography python-future python-pyparsing python-pyelftools cmake ninja-build ccache

install:
 - scripts/install-xtensa.sh
 - scripts/install-idf-v3.2.sh
 - python -m pip install --user -r $IDF_PATH/requirements.txt

script:
 - export IDF_PATH="$HOME/esp-idf"
 - export XTENSA="$HOME/xtensa-esp32-elf"
 - export PATH="$XTENSA/bin:$IDF_PATH/tools:$PATH"
 - scripts/build-firmware.sh
