
/* Copyright 2015-present Samsung Electronics Co., Ltd. and other contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is generated by tools/js2c.py
 * Do not modify this.
 */
#ifndef NODEMCUJS_JS_H
#define NODEMCUJS_JS_H

extern const char console_n[];
extern const uint8_t console_s[];
extern const size_t console_l;

extern const char events_n[];
extern const uint8_t events_s[];
extern const size_t events_l;

extern const char module_n[];
extern const uint8_t module_s[];
extern const size_t module_l;

extern const char nodemcujs_n[];
extern const uint8_t nodemcujs_s[];
extern const size_t nodemcujs_l;

extern const char path_n[];
extern const uint8_t path_s[];
extern const size_t path_l;

extern const char util_n[];
extern const uint8_t util_s[];
extern const size_t util_l;

typedef struct {
  const char* name;
  const void* code;
  const size_t length;
} nodemcujs_js_module_t;

extern const nodemcujs_js_module_t js_modules[];

#endif
