#ifndef NODEMCU_CONFIG_H
#define NODEMCU_CONFIG_H

#include "driver/uart.h"

#define INTERACTIVE_UART_NUM UART_NUM_0
#define INTERACTIVE_UART_BAUDRATE 115200
#define INTERACTIVE_UART_TASK_STACK_DEPTH (1024 * 2)
#define INTERACTIVE_UART_RX_BUF_SIZE (1024 * 2)
#define INTERACTIVE_UART_TX_BUF_SIZE (1024 * 2)

#define PRINT_CHIP_INFO

#endif